python_sources = [
  '__init__.py',
  '_version.py',
  '_fast_s.py',
  '_l1.py',
  '_mm.py',
  '_psifuns.py',
  'd_scale.py',
  'control.py',
  'psi.py',
  'scale.py',
  'lmrob.py',
  'results.py',
  'inference.py',
  'diagnostics.py',
  'formula.py',
  'anova.py',
  'bootstrap.py',
  'ms_estimator.py',
  'outliers.py',
  'rng.py',
  'summary.py',
  '_utils.py',
]

py.install_sources(python_sources, subdir: 'pylmrob')

subdir('_core')
