# SPDX-License-Identifier: GPL-3.0-or-later
"""Parity test: pyrobustlm.lmrob fits with each psi family match R refs.

Compares coefficients and scale to ``tests/reference/stackloss_psi_*.json``
references generated by ``scripts/generate_r_reference.R``.
``robustbase::lmrob`` requires a redescending psi, so ``huber`` is excluded.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from pyrobustlm import Control, lmrob

REPO_ROOT = Path(__file__).resolve().parents[2]
REFERENCE_DIR = REPO_ROOT / "tests" / "reference"


def _ensure_stackloss() -> pd.DataFrame:
    out = REPO_ROOT / "tests" / "data" / "stackloss.csv"
    if not out.exists():
        out.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            [
                "Rscript",
                "-e",
                f"library(robustbase); data(stackloss); write.csv(stackloss, '{out}', row.names=FALSE)",
            ],
            capture_output=True,
            check=True,
        )
    return pd.read_csv(out)


# Per-family rtol on coefficients. ggw rho uses a polynomial approximation
# that introduces a bit of extra slack; lqq's small-x curvature similarly.
_PSI_CASES = [
    ("bisquare", "stackloss_psi_bisquare", 1e-3, 1e-3),
    ("optimal", "stackloss_psi_optimal", 1e-3, 1e-3),
    ("hampel", "stackloss_psi_hampel", 1e-3, 1e-3),
    ("lqq", "stackloss_psi_lqq", 1e-3, 1e-3),
    # ggw rho is a 20-coefficient polynomial approximation (lmrob.c::rho_ggw);
    # the small discretisation error there propagates to ~1.3e-3 in beta.
    ("ggw", "stackloss_psi_ggw", 5e-3, 5e-3),
]


@pytest.mark.parametrize("psi_family,ref_name,rtol_coef,rtol_scale", _PSI_CASES)
def test_lmrob_matches_r_per_family(psi_family, ref_name, rtol_coef, rtol_scale):
    df = _ensure_stackloss()
    ref = json.loads((REFERENCE_DIR / f"{ref_name}.json").read_text())

    ctrl = Control(psi=psi_family, nResample=1000)
    fit = lmrob(
        "stack.loss ~ Air.Flow + Water.Temp + Acid.Conc.",
        df,
        control=ctrl,
        seed=42,
    )
    assert fit.converged_, f"{psi_family}: MM did not converge"

    name_map = {"Intercept": "(Intercept)"}
    r_coefs = ref["coefficients"]
    for name, py_val in zip(fit.term_names_, fit.coef_, strict=True):
        r_key = name_map.get(name, name)
        r_val = float(r_coefs[r_key])
        denom = max(abs(r_val), 1.0)
        assert abs(py_val - r_val) / denom < rtol_coef, (
            f"{psi_family}: coef {name!r} py={py_val} R={r_val}"
        )

    np.testing.assert_allclose(
        fit.scale_,
        float(ref["scale"]),
        rtol=rtol_scale,
        err_msg=f"{psi_family}: scale py={fit.scale_} R={ref['scale']}",
    )
