python_sources = [
  '__init__.py',
  '_version.py',
  '_fast_s.py',
  '_mm.py',
  '_psifuns.py',
  'control.py',
  'psi.py',
  'scale.py',
  'lmrob.py',
  'results.py',
  'inference.py',
  'diagnostics.py',
  'formula.py',
  'ms_estimator.py',
  '_utils.py',
]

py.install_sources(python_sources, subdir: 'pyrobustlm')

subdir('_core')
